# Generated by Django 4.2.1 on 2023-09-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0002_bookauthors"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bookauthors",
            constraint=models.UniqueConstraint(
                fields=("book", "author"), name="book_author_unique"
            ),
        ),
    ]
