# Generated by Django 4.2.1 on 2023-09-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0003_bookauthors_book_author_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
    ]
