# Generated by Django 4.2.1 on 2023-09-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0004_remove_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="authors", to="bookman.author"),
        ),
        migrations.DeleteModel(
            name="BookAuthors",
        ),
    ]
