# Generated by Django 4.2.1 on 2023-09-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0005_book_authors_delete_bookauthors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="bookman.author"),
        ),
    ]
