# Generated by Django 4.2.1 on 2023-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0006_alter_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="bookman.author", verbose_name="著者"),
        ),
    ]
