# Generated by Django 4.2.1 on 2024-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0007_alter_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=256, unique=True, verbose_name="著者名"),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="タイトル"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="カテゴリ名"
            ),
        ),
    ]
