# Generated by Django 6.0.7 on 2026-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookman",
            "0008_alter_author_name_alter_book_name_alter_branch_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="著者名"),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="タイトル"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="remark",
            field=models.CharField(max_length=255),
        ),
    ]
