# Generated by Django 6.0.7 on 2026-07-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0009_alter_author_name_alter_book_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="bookman.book",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="bookman.branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("branch", "book"), name="bookman_assignment_branch_book_unique"
            ),
        ),
    ]
