# Generated by Django 6.0.7 on 2026-07-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0010_alter_assignment_book_alter_assignment_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="amount",
        ),
    ]
