# Generated by Codex on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0011_remove_book_amount"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignment",
            name="bookman_assignment_branch_book_unique",
        ),
        migrations.RenameModel(
            old_name="Assignment",
            new_name="BranchBookStock",
        ),
        migrations.AlterField(
            model_name="branchbookstock",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_stocks",
                to="bookman.book",
            ),
        ),
        migrations.AlterField(
            model_name="branchbookstock",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_stocks",
                to="bookman.branch",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="branches",
            field=models.ManyToManyField(
                related_name="books",
                through="bookman.BranchBookStock",
                to="bookman.branch",
                verbose_name="所蔵支店",
            ),
        ),
        migrations.AddConstraint(
            model_name="branchbookstock",
            constraint=models.UniqueConstraint(
                fields=("branch", "book"), name="bookman_branch_book_stock_unique"
            ),
        ),
    ]
