# Generated by Codex on 2026-07-20

from django.db import migrations, models
import django.db.models.deletion


def migrate_lending_book_to_branch_book_stock(apps, schema_editor):
    Lending = apps.get_model("bookman", "Lending")
    BranchBookStock = apps.get_model("bookman", "BranchBookStock")

    for lending in Lending.objects.all():
        branch_book_stocks = list(
            BranchBookStock.objects.filter(book_id=lending.book_id).order_by("id")
        )
        if len(branch_book_stocks) != 1:
            raise ValueError(
                "Lending.book cannot be migrated to BranchBookStock because "
                f"book_id={lending.book_id} has {len(branch_book_stocks)} stock rows."
            )

        lending.branch_book_stock_id = branch_book_stocks[0].id
        lending.save(update_fields=["branch_book_stock"])


def migrate_lending_branch_book_stock_to_book(apps, schema_editor):
    Lending = apps.get_model("bookman", "Lending")

    for lending in Lending.objects.select_related("branch_book_stock"):
        lending.book_id = lending.branch_book_stock.book_id
        lending.save(update_fields=["book"])


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0012_rename_assignment_to_branch_book_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="lending",
            name="branch_book_stock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lendings",
                to="bookman.branchbookstock",
            ),
        ),
        migrations.RunPython(
            migrate_lending_book_to_branch_book_stock,
            migrate_lending_branch_book_stock_to_book,
        ),
        migrations.RemoveField(
            model_name="lending",
            name="book",
        ),
        migrations.AlterField(
            model_name="lending",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lending",
            name="branch_book_stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lendings",
                to="bookman.branchbookstock",
            ),
        ),
    ]
