# Generated by Codex on 2026-07-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_customer_user_to_customer(apps, schema_editor):
    Customer = apps.get_model("bookman", "Customer")
    Lending = apps.get_model("bookman", "Lending")

    for lending in Lending.objects.select_related("customer_user").all():
        user = lending.customer_user
        customer, _ = Customer.objects.get_or_create(
            name=user.username,
            defaults={"phone": "", "max_lending_count": 5},
        )
        lending.customer_id = customer.id
        lending.save(update_fields=["customer"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookman", "0013_lending_branch_book_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="利用者名"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "max_lending_count",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="貸出上限冊数"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, null=True, verbose_name="更新日"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lending",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lendings",
                to="bookman.customer",
                verbose_name="利用者",
            ),
        ),
        migrations.RunPython(
            migrate_customer_user_to_customer,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="lending",
            name="customer_user",
        ),
        migrations.AlterField(
            model_name="lending",
            name="active",
            field=models.BooleanField(default=True, verbose_name="貸出中"),
        ),
        migrations.AlterField(
            model_name="lending",
            name="branch_book_stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lendings",
                to="bookman.branchbookstock",
                verbose_name="支店別所蔵",
            ),
        ),
        migrations.AlterField(
            model_name="lending",
            name="contact_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to=settings.AUTH_USER_MODEL,
                verbose_name="対応者",
            ),
        ),
        migrations.AlterField(
            model_name="lending",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="貸出登録日"),
        ),
        migrations.AlterField(
            model_name="lending",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lendings",
                to="bookman.customer",
                verbose_name="利用者",
            ),
        ),
        migrations.AlterField(
            model_name="lending",
            name="return_date",
            field=models.DateField(verbose_name="返却予定日"),
        ),
        migrations.AlterField(
            model_name="lending",
            name="updated_at",
            field=models.DateField(auto_now=True, null=True, verbose_name="更新日"),
        ),
    ]
