# Generated by Django 6.0.7 on 2026-07-20 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_contact_user_to_library_staff(apps, schema_editor):
    LibraryStaff = apps.get_model("bookman", "LibraryStaff")
    Lending = apps.get_model("bookman", "Lending")

    staff_by_user_id = {}
    for lending in Lending.objects.select_related("contact_user").all():
        user = lending.contact_user
        staff = staff_by_user_id.get(user.id)
        if staff is None:
            staff, _ = LibraryStaff.objects.get_or_create(
                user_id=user.id,
                defaults={"name": user.username, "role": ""},
            )
            staff_by_user_id[user.id] = staff

        lending.contact_staff_id = staff.id
        lending.save(update_fields=["contact_staff"])


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0014_customer_lending_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="職員名"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="権限種別"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, null=True, verbose_name="更新日"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_members",
                        to="bookman.branch",
                        verbose_name="所属支店",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_staff",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="認証ユーザー",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lending",
            name="contact_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="bookman.librarystaff",
                verbose_name="対応者",
            ),
        ),
        migrations.RunPython(
            migrate_contact_user_to_library_staff,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="lending",
            name="contact_user",
        ),
        migrations.AlterField(
            model_name="lending",
            name="contact_staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="bookman.librarystaff",
                verbose_name="対応者",
            ),
        ),
    ]
