# Generated by Django 6.0.7 on 2026-07-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0015_remove_lending_contact_user_librarystaff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="librarystaff",
            name="user",
        ),
    ]
