# Generated by Django 6.0.7 on 2026-07-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0016_remove_librarystaff_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "予約待ち"),
                            ("held", "取り置き中"),
                            ("canceled", "取消済み"),
                            ("expired", "期限切れ"),
                            ("fulfilled", "貸出済み"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="予約状態",
                    ),
                ),
                (
                    "hold_expires_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="取り置き期限日"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="予約登録日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, null=True, verbose_name="更新日"),
                ),
                (
                    "branch_book_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="bookman.branchbookstock",
                        verbose_name="支店別所蔵",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="bookman.customer",
                        verbose_name="利用者",
                    ),
                ),
            ],
        ),
    ]
