# Generated by Django 6.0.7 on 2026-07-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0017_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="lending",
            name="original_return_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="補正前返却予定日"
            ),
        ),
        migrations.AddField(
            model_name="lending",
            name="return_date_adjustment_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="返却予定日補正理由"
            ),
        ),
        migrations.CreateModel(
            name="BranchClosedDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="休館日")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="休館理由"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, null=True, verbose_name="更新日"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closed_days",
                        to="bookman.branch",
                        verbose_name="支店",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "date"),
                        name="bookman_branch_closed_day_unique",
                    )
                ],
            },
        ),
    ]
