# Generated by Django 6.0.7 on 2026-07-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0018_lending_original_return_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_screen",
                    models.CharField(max_length=100, verbose_name="対象画面"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="保存条件名")),
                ("conditions", models.JSONField(verbose_name="検索条件JSON")),
                (
                    "share_scope",
                    models.CharField(
                        choices=[
                            ("personal", "個人"),
                            ("branch", "支店共有"),
                            ("admin", "管理者共有"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="共有範囲",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        default="staff", max_length=20, verbose_name="所有者種別"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, null=True, verbose_name="更新日"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_conditions",
                        to="bookman.branch",
                        verbose_name="対象支店",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_conditions",
                        to="bookman.librarystaff",
                        verbose_name="作成職員",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_screen", "name", "created_by"),
                        name="bookman_search_condition_unique_owner_name",
                    )
                ],
            },
        ),
    ]
