# Generated by Django 6.0.7 on 2026-07-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0021_book_isbn_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="remark",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
