# Generated by Django 6.0.7 on 2026-07-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookman", "0022_alter_branch_remark"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="branch",
            table=None,
        ),
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
        migrations.AlterModelTable(
            name="municipality",
            table=None,
        ),
    ]
